
export const cities = [
  "Mumbai, Maharashtra",
  "Delhi, Delhi",
  "Bengaluru, Karnataka",
  "Ahmedabad, Gujarat",
  "Hyderabad, Telangana",
  "Chennai, Tamil Nadu",
  "Kolkata, West Bengal",
  "Pune, Maharashtra",
  "Jaipur, Rajasthan",
  "Surat, Gujarat",
  "Lucknow, Uttar Pradesh",
  "Kanpur, Uttar Pradesh",
  "Nagpur, Maharashtra",
  "Indore, Madhya Pradesh",
  "Thane, Maharashtra",
  "Bhopal, Madhya Pradesh",
  "Visakhapatnam, Andhra Pradesh",
  "Pimpri-Chinchwad, Maharashtra",
  "Patna, Bihar",
  "Vadodara, Gujarat",
  "Ghaziabad, Uttar Pradesh",
  "Ludhiana, Punjab",
  "Agra, Uttar Pradesh",
  "Nashik, Maharashtra",
  "Faridabad, Haryana",
  "Meerut, Uttar Pradesh",
  "Rajkot, Gujarat",
  "Kalyan-Dombivali, Maharashtra",
  "Vasai-Virar, Maharashtra",
  "Varanasi, Uttar Pradesh",
  "Srinagar, Jammu and Kashmir",
  "Aurangabad, Maharashtra",
  "Dhanbad, Jharkhand",
  "Amritsar, Punjab",
  "Navi Mumbai, Maharashtra",
  "Allahabad, Uttar Pradesh",
  "Ranchi, Jharkhand",
  "Howrah, West Bengal",
  "Coimbatore, Tamil Nadu",
  "Jabalpur, Madhya Pradesh",
  "Gwalior, Madhya Pradesh",
  "Vijayawada, Andhra Pradesh",
  "Jodhpur, Rajasthan",
  "Madurai, Tamil Nadu",
  "Raipur, Chhattisgarh",
  "Kota, Rajasthan",
  "Guwahati, Assam",
  "Chandigarh, Chandigarh",
  "Solapur, Maharashtra",
  "Hubli-Dharwad, Karnataka",
  "Bareilly, Uttar Pradesh",
  "Moradabad, Uttar Pradesh",
  "Mysore, Karnataka",
  "Gurgaon, Haryana",
  "Aligarh, Uttar Pradesh",
  "Jalandhar, Punjab",
  "Tiruchirappalli, Tamil Nadu",
  "Bhubaneswar, Odisha",
  "Salem, Tamil Nadu",
  "Mira-Bhayandar, Maharashtra",
  "Thiruvananthapuram, Kerala",
  "Bhiwandi, Maharashtra",
  "Saharanpur, Uttar Pradesh",
  "Gorakhpur, Uttar Pradesh",
  "Guntur, Andhra Pradesh",
  "Bikaner, Rajasthan",
  "Amravati, Maharashtra",
  "Noida, Uttar Pradesh",
  "Jamshedpur, Jharkhand",
  "Bhilai, Chhattisgarh",
  "Cuttack, Odisha",
  "Firozabad, Uttar Pradesh",
  "Kochi, Kerala",
  "Nellore, Andhra Pradesh",
  "Bhavnagar, Gujarat",
  "Dehradun, Uttarakhand",
  "Durgapur, West Bengal",
  "Asansol, West Bengal",
  "Rourkela, Odisha",
  "Nanded, Maharashtra",
  "Kolhapur, Maharashtra",
  "Ajmer, Rajasthan",
  "Gulbarga, Karnataka",
  "Jamnagar, Gujarat",
  "Ujjain, Madhya Pradesh",
  "Loni, Uttar Pradesh",
  "Siliguri, West Bengal",
  "Jhansi, Uttar Pradesh",
  "Ulhasnagar, Maharashtra",
  "Jammu, Jammu and Kashmir",
  "Sangli-Miraj & Kupwad, Maharashtra",
  "Mangalore, Karnataka",
  "Erode, Tamil Nadu",
  "Belgaum, Karnataka",
  "Ambattur, Tamil Nadu",
  "Tirunelveli, Tamil Nadu",
  "Malegaon, Maharashtra",
  "Gaya, Bihar",
  "Tiruppur, Tamil Nadu",
  "Davanagere, Karnataka",
  "Kozhikode, Kerala",
  "Akola, Maharashtra",
  "Kurnool, Andhra Pradesh",
  "Bokaro Steel City, Jharkhand",
  "Rajahmundry, Andhra Pradesh",
  "Ballari, Karnataka",
  "Agartala, Tripura",
  "Bhagalpur, Bihar",
  "Latur, Maharashtra",
  "Dhule, Maharashtra",
  "Korba, Chhattisgarh",
  "Bhilwara, Rajasthan",
  "Brahmapur, Odisha",
  "Muzaffarpur, Bihar",
  "Ahmednagar, Maharashtra",
  "Mathura, Uttar Pradesh",
  "Kollam, Kerala",
  "Avadi, Tamil Nadu",
  "Kadapa, Andhra Pradesh",
  "Kamarhati, West Bengal",
  "Sambalpur, Odisha",
  "Bilaspur, Chhattisgarh",
  "Shahjahanpur, Uttar Pradesh",
  "Satara, Maharashtra",
  "Bijapur, Karnataka",
  "Rampur, Uttar Pradesh",
  "Shivamogga, Karnataka",
  "Chandrapur, Maharashtra",
  "Junagadh, Gujarat",
  "Thrissur, Kerala",
  "Alwar, Rajasthan",
  "Bardhaman, West Bengal",
  "Kulti, West Bengal",
  "Kakinada, Andhra Pradesh",
  "Nizamabad, Telangana",
  "Parbhani, Maharashtra",
  "Tumkur, Karnataka",
  "Hisar, Haryana",
  "Ozhukarai, Puducherry",
  "Bihar Sharif, Bihar",
  "Panipat, Haryana",
  "Darbhanga, Bihar",
  "Bally, West Bengal",
  "Aizawl, Mizoram",
  "Dewas, Madhya Pradesh",
  "Ichalkaranji, Maharashtra",
  "Karnal, Haryana",
  "Bathinda, Punjab",
  "Jalna, Maharashtra",
  "Eluru, Andhra Pradesh",
  "Kirari Suleman Nagar, Delhi",
  "Barasat, West Bengal",
  "Panihati, West Bengal",
  "Sagar, Madhya Pradesh",
  "Mau, Uttar Pradesh",
  "Rohtak, Haryana",
  "Arrah, Bihar",
  "Anantapur, Andhra Pradesh",
  "Karimnagar, Telangana",
  "Etawah, Uttar Pradesh",
  "Ambernath, Maharashtra",
  "Bharatpur, Rajasthan",
  "Begusarai, Bihar",
  "New Delhi, Delhi",
  "Gandhidham, Gujarat",
  "Baranagar, West Bengal",
  "Tiruvottiyur, Tamil Nadu",
  "Puducherry, Puducherry",
  "Sikar, Rajasthan",
  "Thoothukudi, Tamil Nadu",
  "Rewa, Madhya Pradesh",
  "Mirzapur, Uttar Pradesh",
  "Raichur, Karnataka",
  "Pali, Rajasthan",
  "Khammam, Telangana",
  "Vizianagaram, Andhra Pradesh",
  "Katihar, Bihar",
  "Haridwar, Uttarakhand",
  "Sri Ganganagar, Rajasthan",
  "Karawal Nagar, Delhi",
  "Nagercoil, Tamil Nadu",
  "Mango, Jharkhand",
  "Bulandshahr, Uttar Pradesh",
  "Thanjavur, Tamil Nadu",
  "Vapi, Gujarat",
];
